requires 'perl', '5.010';

requires 'Moo', '2.0';
requires 'Try::Tiny', '>= 0.20';
requires 'JSON::MaybeXS';
requires 'LWP::UserAgent', '6.0';
requires 'HTTP::Request', '6.0';

on 'test' => sub {
    requires 'Test::More', '0.96';
    requires 'Test::Exception';
};

on 'develop' => sub {
    requires 'Dist::Zilla';
    recommends 'Pod::Coverage::TrustPod';
};
